var tian = document.getElementsByClassName("day_one")[0]
	var shi = document.getElementById("shangou_date_shi")
	var fen = document.getElementById("shangou_date_fen")
	var miao = document.getElementById("shangou_date_miao")
	function setTime(){
		var dt = new Date()
		var dt1 = new Date()
		dt.setFullYear(2020,10,11)
		dt.setHours(00)
		dt.setMinutes(00)
		dt.setSeconds(00)
		dt.setMilliseconds(00)
		var dao = dt.getTime() - dt1.getTime()
		tian.innerHTML = Math.floor(dao / 1000 / 60 / 60 /24)
		shi.innerHTML = Math.floor(dao / 1000 / 60 / 60 %  24)
		fen.innerHTML =  Math.floor(dao / 1000 / 60 % 60 )
		miao.innerHTML = Math.floor(dao / 1000 % 60 )
	}
	setTime()
	setInterval(setTime,1000)
